### PR TITLE
Add binary sensor support

### PR DESCRIPTION
**Pull request by abstractionnl**
Add binary sensor support through the binary_sensor platform
Cleaned up the WiCan entity code.

### CODE REVIEW

**Comment by abstractionnl** [comment]
@jay-oswald Could you review this? I want to continue developing some more features based on this.

**Comment by jay-oswald** [comment]
Sorry been busy and away, wont be able to have a proper look and test for another few days, but just having a look on phone it looks pretty good, doubt there will be any major issues and changes needed, if you did want to start on the next thing

**Comment by jay-oswald** [comment]
Haven't been able to giver it a proper test, but looking good, just going to merge it but not do a release till I've had the chance to do a proper test, even if theres some bugs the structutal changes and using the coordinator is much better anyway

**Comment by jmalm** [comment]
I tried to run with the latest state of the master branch, including this change, but got the following and all entities unavailable (integration restarted when the WiCAN device was online):

```
homeassistant  | 2025-01-06 15:49:34.844 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up wican platform for binary_sensor
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
homeassistant  |     await asyncio.shield(awaitable)
homeassistant  |   File "/config/custom_components/wican/binary_sensor.py", line 79, in async_setup_entry
homeassistant  |     if coordinator.data["pid"][key]["sensor_type"] == "binary_sensor":
homeassistant  |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
homeassistant  | KeyError: 'sensor_type'
homeassistant  | 2025-01-06 15:49:34.848 INFO (MainThread) [homeassistant.components.sensor] Setting up wican.sensor
homeassistant  | 2025-01-06 15:49:34.849 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up wican platform for sensor
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
homeassistant  |     await asyncio.shield(awaitable)
homeassistant  |   File "/config/custom_components/wican/sensor.py", line 63, in async_setup_entry
homeassistant  |     if coordinator.data["pid"][key]["sensor_type"] != "binary_sensor":
homeassistant  |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
homeassistant  | KeyError: 'sensor_type'
```

**Comment by abstractionnl** [comment]
What version of the Wican are you running? It looks like it's missing the sensor_type key in the list of sensors that are returned by the Wican.

I cannot test this anymore because I switched to a more powerfull esphome/mqtt implementation.

**Comment by jwiesel** [comment]
Hi @abstractionnl , I have the same issue reported by @jmalm running the latest version of WiCAN (4.04.) and HomeAssistant (2025.1.4) when reloading the integration (files downloaded to wican folder from master branch).

Any idea, how to fix the issue?

**Log-Entry 1:**
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:366

_Error while setting up wican platform for binary_sensor_
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
>     await asyncio.shield(awaitable)
>   File "/config/custom_components/wican/binary_sensor.py", line 79, in async_setup_entry
>     if coordinator.data["pid"][key]["sensor_type"] == "binary_sensor":
>        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
> KeyError: 'sensor_type'

**Log-Entry 2:**
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:366

_Error while setting up wican platform for sensor_
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
>     await asyncio.shield(awaitable)
>   File "/config/custom_components/wican/sensor.py", line 63, in async_setup_entry
>     if coordinator.data["pid"][key]["sensor_type"] != "binary_sensor":
>        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
> KeyError: 'sensor_type'

**Comment by jwiesel** [comment]
I just did some debugging and might have found the root cause:

The pid-data received from WiCAN does not contain a key called "sensor_type" for any of the records (tested with default "Hyundai Kona" car profile) - see exemplary data below

Commenting out line 63 and removing some blanks in the following lines prevents the issue of the missing key.
Then also the units are shown correctly in HomeAssistant (e.g. SOC 41%)

**WiCAN Coordinator log: [custom_components.wican.coordinator]**
> 'pid':
> 	{
> 	  'SOC_BMS':
> 	  {
> 	  'class': 'battery',
> 	  'unit': '%',
> 	  'value': 41.5
> 	  },
> 	  'Max_REGEN':
> 	  {
> 	  'class': 'power',
> 	  'unit': 'kW',
> 	  'value': 0
> 	  },
> 	  'Max_Power':
> 	  {
> 	  'class': 'power',
> 	  'unit': 'kW',
> 	  'value': 0
> 	  },
> 	}
>

**Comment by abstractionnl** [comment]
I think the sensor_type might not be given by WiCan, but I did add in this PR: 
https://github.com/meatpiHQ/wican-fw/pull/244/files#diff-538a4cf49037f8ccc0deabb244a823b4fb636b5a56a5ac6c3fdf92572b3e66b2R638

This was refactored and moved by meatpi and forgotten to add the sensor_type key:

https://github.com/meatpiHQ/wican-fw/blob/main/main/autopid.c#L528

**Pull request merged**
